sqlccpjt/dbmnt/urls.py
from django.urls import path
from django.conf.urls import include, url
from dbmnt.views import *

urlpatterns = [
    url(r'^$', DbMntLV.as_view(), name='dbmnt'), #프로젝트리스트를 조회
]

sqlccpjt/pjtmgmt/urls.py
from django.urls import path
from django.conf.urls import include, url
from pjtmgmt.views import *
#from . import views

urlpatterns = [
    url(r'^$', SqlcProjectLV.as_view(), name='pjtlist'), #프로젝트리스트를 조회
    url(r'^addpjt/$', SqlcProjectCV.as_view(), name='addpjt'), #프로젝트를 등록
    path('<int:pk>/update/', SqlcProjectUV.as_view(), name='updatepjt'), #프로젝트를 수정
    path('<int:pk>/delete/', SqlcProjectDeleteView.as_view(), name='delpjt'), # 프로젝트를 삭제
    path('<int:pk>/detail/', SqlcProjectDV.as_view(), name='detailpjt'), # 프로젝트 상세보기
    path('<int:pk>/addserver/', MntServerCV.as_view(), name='addserver'), # 모니터링 서버  등록
    path('<int:pk>/updateserver/', MntServerUV.as_view(), name='updateserver'), #모니터링 서버 정보 수정
    path('<int:pk>/deleteserver/', MntServerDeleteView.as_view(), name='delserver'), #모니터링 서버 삭제

    path(r'<int:pk>/addgroup/', MntGroupCV.as_view(), name='addgroup'), # 모니터링 그룹 등록
    path(r'<int:pk>/detailmntgrp/', MntGroupDV.as_view(), name='detailmntgrp'), #모니터링그룹 상세 조회

    path(r'<int:pk>/<int:pjtid>/addmntuser/', MntGroupUserCV.as_view(), name='addmntuser'), # 모니터링 그룹 사용자 추가
    path(r'<int:pk>/<int:pjtid>/addmntserver/', MntGroupServerCV.as_view(), name='addmntserver'), # 모니터링 그룹 서버  추가



]

sqlccpjt/wingstone/urls.py
from django.contrib import admin
from django.urls import path,  include
from django.conf import settings
from django.conf.urls import url
from wingstone.views import SqlcHomeView, SqlcUserCreateView, SqlcUserCreateDoneTV


urlpatterns = [
    #url(r'^admin/',include(admin.site.urls),name=None),
    path('admin/', admin.site.urls),
    url(r'^$',SqlcHomeView.as_view(), name='sqlchome'),
    url(r'^pjtmgmt/', include('pjtmgmt.urls')),
    url(r'^dbmnt/', include('dbmnt.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/$', SqlcUserCreateView.as_view(), name='register'),
    url(r'^accounts/register/done/$', SqlcUserCreateDoneTV.as_view(), name='register_done'),

]

sqlccpjt/pjtmgmt/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model


# Create your models here.

def get_sentinel_user():
    return get_user_model().objects.get_or_create(username='do not exist')[0]

"""
현재 자동으로 가입으로 처리 필요
상품에 따른 프로젝트에서 만들 수 있는 서버수, 사용자 수를 제한한다. 
"""
class SqlcProject(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET(get_sentinel_user), )
    created_dt = models.DateTimeField(default=datetime.now, blank=False)
    project_nm = models.CharField(max_length=255, help_text="프로젝트 명칭", null=False)
    project_desc = models.TextField(null=False, blank=False)
    sta_eff_dt = models.CharField(max_length=8, null=False, blank=False)
    end_eff_dt = models.CharField(max_length=8, null=False, blank=False)
    prod_id = models.ForeignKey('SqlcProd', on_delete=models.CASCADE)
    mnt_is_run = models.BooleanField(default=False)
    mnt_status = models.CharField(default="미수행", max_length=10)

    """
    결제 여부등 추후 별도 관리 필요 
    """
    def __str__(self):
        return self.project_nm

class SqlcProd(models.Model):
    prod_id = models.CharField(max_length=80)
    prod_nm = models.CharField(max_length=255)
    prod_desc = models.TextField()
    created_dt = models.DateTimeField(default=datetime.now, blank=False)
    sta_eff_dt = models.CharField(max_length=8)
    end_eff_dt = models.CharField(max_length=8)
    tot_user_qty = models.DecimalField(max_digits=5, decimal_places=0)
    tot_server_qty = models.DecimalField(max_digits=5, decimal_places=0)

    def __str__(self):
        return self.prod_nm

    #pay_yn = models.CharField(max_length=8, null=False, blank=False)



class MntServer(models.Model):
    project = models.ForeignKey('SqlcProject', on_delete=models.CASCADE)
    created_dt = models.DateTimeField(default=datetime.now, blank=False)
    server_nm = models.CharField(max_length=255, null=True)
    db_server_ip = models.CharField(max_length=20, null=True)
    db_access_port = models.DecimalField(max_digits=6, decimal_places=0)
    db_acnt_id = models.CharField(max_length=20, null=True)
    db_acnt_pwd = models.CharField(max_length=20, null=True)
    is_available = models.BooleanField(default=False)
    server_desc = models.TextField()

    def __str__(self):
        return self.server_nm + " ( " + self.project.project_nm + " ) "


class ChkPrivilege(models.Model):
    prv_id = models.CharField(max_length=255)
    # prv_id = server_nm = models.CharField(max_length=255, null=False)


"""
class MntServers(db.Document):
    project = db.ReferenceField(MntProjects, required=True)  # reverse_delete_rule=mongoengine.NULLIFY)
    owner = db.ReferenceField(User, required=True)
    created_at = db.DateTimeField(default=datetime.now, required=True)


    server_nm = db.StringField(max_Length=255, required=True)
    # project_id = db.StringField(max_Length=10, required=True)
    # project_nm = db.StringField(max_Length=10, required=True)
    # server_id = db.StringField(max_Length=10, required=True)
    # mgmt_user_id = db.StringField(max_Length=255, required=True)
    # server_cl_cd = db.StringField(
    #     max_Length=2,
    #     required=True,
    #     default='DB',
    #     choices=SERVER_TYPE_CHOICES)

    host_ip = db.StringField(max_Length=20, required=True)
    port = db.IntField(required=True)

    desc = db.StringField(max_Length=500, required=True)
    used_yn = db.StringField(max_Length=1, required=True, default='Y')
    schema = db.ListField()
    db_user_acnt_list = db.ListField()

    # os에 대한 계정정보
    acnt_id = db.StringField(max_Length=10, required=True)
    pwd = db.StringField(max_Length=100, required=True)
    # db에 대한 계정정보
    db_acnt_nm = db.StringField(max_Length=20)
    db_acnt_pwd = db.StringField(max_Length=20)

    def clean(self):
        # self.project_id = self.project.project_id
        # self.project_nm = self.project.project_nm
        # self.server_id = 'dummy'
        # self.mgmt_user_id = 'dummy'
        self.desc = "dummy"
        self.owner = self.project.owner

        # db의 경우는 계정데이터를 옮겨준다. 별도 관리하기 때문에
        # if self.server_cl_cd == 'DB':
        #     self.db_acnt_nm = self.acnt_id
        #     self.db_acnt_pwd = self.pwd

    def __str__(self):
        return f'{self.server_nm}({self.host_ip})'
"""
"""
모니터링 그룹 해당 프로젝트의 모니터링 그룹 
"""
class MntGroup(models.Model):
    project = models.ForeignKey('SqlcProject', on_delete=models.CASCADE)
    mnt_group_nm = models.CharField(max_length=255, null=False, default="모니터링 그룹 명칭을 등록하세요")
    created_dt = models.DateTimeField(default=datetime.now, blank=False)
    mnt_group_desc = models.TextField(default="그룹에 대한 설명을 적어 주세요")

    def __str__(self):
        return self.mnt_group_nm + " ( " + self.project.project_nm + " ) "


"""
모니터링 그룹별 관리 서버 
"""

class MntGroupServer(models.Model):
    project = models.ForeignKey('SqlcProject', on_delete=models.CASCADE)
    mntgroup = models.ForeignKey('MntGroup', on_delete=models.CASCADE)
    ava_server = models.ForeignKey('MntServer', on_delete=models.CASCADE)

    created_dt = models.DateTimeField(default=datetime.now, blank=False)

    def __str__(self):
        return self.mntgroup.mnt_group_nm + " ( " + self.ava_server.server_nm + " ) "


"""
모니터링 그룹별 사용자 
"""

class MntGroupUser(models.Model):
    project = models.ForeignKey('SqlcProject', on_delete=models.CASCADE)
    mntgroup = models.ForeignKey('MntGroup', on_delete=models.CASCADE)
    mntUser = models.ForeignKey('auth.User', on_delete=models.CASCADE)

    created_dt = models.DateTimeField(default=datetime.now, blank=False)

    def __str__(self):
        return self.mntgroup.mnt_group_nm




"""
프로젝트로서 
오너, 생성일자, 유효기간(일자)를 관리한다. 
미사용  
"""


class SqlcProjects(models.Model):
    ownername = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_dt = models.DateTimeField(default=datetime.now, blank=False)
    project_nm = models.CharField(max_length=255)
    project_desc = models.TextField()
    sta_eff_dt = models.CharField(max_length=8)
    end_eff_dt = models.CharField(max_length=8)
    prod_id = models.ForeignKey('SqlcProd', on_delete=models.CASCADE)

    def __str__(self):
        return self.project_nm

    def get_absolute_url(self):
        return reverse('updatepjt', kwargs={'pk': self.pk})

sqlccpjt/pjtmgmt/forms.py
from django.forms import ModelForm
from pjtmgmt.models import *
from django.contrib.auth.models import User
from django import forms

"""
프로젝트를 등록하는 폼 
"""
class SqlcProjectForm(ModelForm):

    def __init__(self, *args, **kwargs):

        owner = kwargs.pop('user', None)

        super(SqlcProjectForm, self).__init__(*args, **kwargs)
        self.fields['owner'].queryset = User.objects.filter(username=owner.username)


    class Meta:
        model = SqlcProject
        exclude =['created_dt']


"""
서버 추가를 등록하는 폼 
"""
class SqlcServerForm(ModelForm):

    def __init__(self, *args, **kwargs):

        pjtid = kwargs.pop('pjtid', None)
        super(SqlcServerForm, self).__init__(*args, **kwargs)
        self.fields['project'].queryset = SqlcProject.objects.filter(id=pjtid)


    class Meta:
        model = MntServer
        exclude =['created_dt']


"""
모니터링 그룹과 서버, 사용자를 mapping 하는 폼
"""
class MntGroupForm(ModelForm):

    def __init__(self, *args, **kwargs):
        pjtid = kwargs.pop('pjtid', None)
        super(MntGroupForm, self).__init__(*args, **kwargs)
        self.fields['project'].queryset = SqlcProject.objects.filter(id=pjtid)

    class Meta:
        model = MntGroup
        exclude =['created_dt']


"""
"""



### 폼에서 disable 처리하는 법 적용하기
class ProjectForm(ModelForm):

    #ownername = forms.CharField()


    """
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        print(instance)
        if instance and instance.id:
            print('ccc')
            self.fields['sta_eff_dt'].widget.attrs['readonly'] = True


    def clean_sta_eff_dt(self):
        instance = getattr(self, 'instance', None)
        print(instance)
        print('xxxx')
        if instance and instance.id:
            print('xxxx2')
            return instance.sta_eff_dt
        else:
            print('xxxx3')
            return self.cleaned_data['sta_eff_dt']

    """
    def __init__(self, *args, **kwargs):
        #user = kwargs.pop('user')
        super(ProjectForm, self).__init__(*args, **kwargs)
        #self.fields['ownername'].queryset = user
        #self.fields['ownername'].widget.attrs['id'] = 'ownername'
        #self.fields['ownername'].widget.attrs['onChange'] = 'alert("test");'
        #self.fields['ownername'].queryset = User.objects.get(username = ownername)
        #self.fields['ownername'].widget.attrs['id'] = 'ownername'


    class Meta:
        model = SqlcProjects
        exclude =['created_dt']

        #widgets = {
        #    'sta_eff_dt': forms.CharField(attrs={'readonly': True}),
        #    'end_eff_dt': forms.CharField(attrs={'readonly': True}),
        #    'end_eff_dt': forms.CharField(attrs={'readonly': True})
        # }


        # snip the other fields for the sake of brevity
        # Adding content to the form
        #self.fields['ownername'] = self.request.user


    #def __init__(self, initial=None):
    #    self.initial_extra = initial
        #self.fields = getattr(option,'sta_eff_dt',)
        #def __init__(self,user_id):
        #    self.fields['ownername'] = user_id





"""
모니터링 사용자를 등록하는 폼 
"""
class MntGroupUserForm(forms.Form):

    username = forms.EmailField(required=True)

    def save(self, pjt_id, mntgrp_id, email, commit=True):

        #mnt = MntGroup.objects.filter(id=mntgrp_id)
        #pjt = SqlcProject.objects.get(id=pjt_id)
        #user = User.objects.get(username=email)
        print('------start---------')
        #print(mnt)
        #print(pjt)
        #print(user)
        print('------end---------')

        mntgrpuser = MntGroupUser(project=SqlcProject.objects.get(id=pjt_id), mntgroup=MntGroup.objects.get(id=mntgrp_id), mntUser=User.objects.get(username=email))
        mntgrpuser.save()


"""
모니터링 그룹에 서버를 매핑하기 위한 폼 
"""

class MntGroupServerForm(ModelForm):

    def __init__(self, *args, **kwargs):

        pjtid = kwargs.pop('pjtid', None)
        mntid = kwargs.pop('mntid', None)
        super(MntGroupServerForm, self).__init__(*args, **kwargs)

        self.fields['project'].queryset = SqlcProject.objects.filter(id=pjtid)
        self.fields['mntgroup'].queryset = MntGroup.objects.filter(id=mntid)
        self.fields['ava_server'].queryset = MntServer.objects.filter(project=SqlcProject.objects.get(id=pjtid))

    class Meta:
        model = MntGroupServer
        exclude = ['created_dt']


"""
    def __init__(self, *args, **kwargs):
        pjtid = kwargs.pop('pjtid', None)
        super(MntGroupUserForm, self).__init__(*args, **kwargs)
        #self.fields['project'].queryset = SqlcProject.objects.filter(id=pjtid)

    class Meta:
        model = MntGroupUserForm
        exclude =['created_dt',]

"""

sqlccpjt/pjtmgmt/templates/pjtmgmt/add_mntgrpserver.html
{% extends "base.html" %}
{% load staticfiles %}
{% block divinfo %} <div id="wrap" ><!-- wrap start --> {% endblock %}
{% block content %}
<section class="contents"><!-- contents start -->
<form action="." method="post"> {% csrf_token %}
  {{ form.non_field_errors }}
  {{ form.source.errors }}
  {{ form.source }}

{% for mnt in mntgrpnm %}
    <h2 class="level2">{{ mnt.mnt_group_nm }} 모니터링 그룹 서버 추가 </h2>
    <table class="type2 mt30"><!-- table start -->
    <caption>table</caption>
    <colgroup>
	    <col style="width:220px" />
	    <col style="width:*" />
    </colgroup>
    <tbody>
    <!--
    <tr>
	    <th scope="row"> 프로젝트 선택  </th>
        <td>{{ form.project.errors }} {{ form.project }} </td>
    </tr>
    <tr>
	    <th scope="row"> 모니터링그룹 선택 </th>
        <td>{{ form.mntgroup.errors }} {{ form.mntgroup }} </td>
    </tr>
    -->
    <tr>
	    <th scope="row"> 서버 선택 </th>
        <td>{{ form.ava_server.errors }} {{ form.ava_server }} </td>
    </tr>

    </tbody>
    </table><!-- table end -->

    <ul class="center_btns">
    <li> <button class="btn big btn_orange" type="submit">서버 추가 </button></li>
    </ul>
    </br>

    <ul class="list_style"><!-- list_style start -->
        <h2 class="level2"> 등록 사용자 리스트 </h2> </br></br>
        {% for mntuser in mnt.mntgroupuser_set.all %}
        <li> <strong> {{ mntuser.mntUser }} </strong> <p class="subject"><a href=""> 유저정보&nbsp;:&nbsp;<span> {{ mntuser.mntUser.username }} </a></p> </li>
        {% endfor %}
        </br></br></br>

        <h2 class="level2"> 등록 서버 리스트 </h2>
        {% for mntserver in mnt.mntgroupserver_set.all %}

        <li><strong> {{ mntserver.ava_server.server_nm }}  </strong> <p class="subject"> <a href="#"> 서버IP정보 :&nbsp;<span> {{ mntserver.ava_server.db_server_ip}} &nbsp;&nbsp; </span> 생성일:&nbsp;  <span> {{ mntserver.ava_server.created_dt }} </span> </a></p></li>
        {% endfor %}
        </br>
    </ul> <!-- list_style end -->

{% endfor %}
</form>
</section><!-- contents end -->

<!-- </section> --> <!-- container end -->
<hr />
{% endblock %}

sqlccpjt/pjtmgmt/templates/pjtmgmt/add_mntgrpuser.html
{% extends "base.html" %}
{% load staticfiles %}
{% block divinfo %} <div id="wrap" ><!-- wrap start --> {% endblock %}
{% block content %}
<section class="contents"><!-- contents start -->
<form action="." method="post"> {% csrf_token %}
  {{ form.non_field_errors }}
  {{ form.source.errors }}
  {{ form.source }}


{% for mnt in mntgrpnm %}

    <h2 class="level2">{{ mnt.mnt_group_nm }} 모니터링 그룹 사용자 추가 </h2>
    <table class="type2 mt30"><!-- table start -->
    <caption>table</caption>
    <colgroup>
	    <col style="width:220px" />
	    <col style="width:*" />
    </colgroup>
    <tbody>
    <tr>
	    <th scope="row"> 사용자 email 입력 </th>
        <td>{{ form.username.errors }} {{ form.username }} </td>
    </tr>
    </tbody>
    </table><!-- table end -->

    <ul class="center_btns">
    <li> <button class="btn big btn_orange" type="submit">사용자 추가 </button></li>
    </ul>
    </br>

    <ul class="list_style"><!-- list_style start -->
        <h2 class="level2"> 등록 사용자 리스트 </h2> </br></br>
        {% for mntuser in mnt.mntgroupuser_set.all %}
        <li> <strong> {{ mntuser.mntUser }} </strong> <p class="subject"><a href=""> 유저정보&nbsp;:&nbsp;<span> {{ mntuser.mntUser.username }} </a></p> </li>
        {% endfor %}
        </br></br></br>

        <h2 class="level2"> 등록 서버 리스트 </h2>
        {% for mntserver in mnt.mntgroupserver_set.all %}
        <li><strong> {{ mntserver.ava_server.server_nm }}  </strong> <p class="subject"> <a href="#"> 서버IP정보 :&nbsp;<span> {{ mntserver.ava_server.db_server_ip}} &nbsp;&nbsp; </span> 생성일:&nbsp;  <span> {{ mntserver.ava_server.created_dt }} </span> </a></p></li>
        {% endfor %}
        </br>
    </ul> <!-- list_style end -->

{% endfor %}

</form>
</section><!-- contents end -->

<!-- </section> --> <!-- container end -->
<hr />
{% endblock %}

sqlccpjt/pjtmgmt/templates/pjtmgmt/detail_mntgroup.html
{% extends "base.html" %}
{% load staticfiles %}
{% block divinfo %} <div id="wrap" ><!-- wrap start --> {% endblock %}
{% block content %}
<section class="container"><!-- container start -->

<section class="contents"><!-- contents start -->
<form action="#" method="post">{% csrf_token %}

<h2 class="level2"> {{ object.mnt_group_nm }} 모니터링 그룹 정보 </h2>

<table class="type2 mt30"><!-- table start -->
<caption>table</caption>
<colgroup>
	<col style="width:220px" />
	<col style="width:*" />
</colgroup>
<tbody>
<tr>
	<th scope="row">소속 프로젝트</th>
    <td>{{ object.project.project_nm.errors }} {{ object.project.project_nm }} </td>
	<!-- <td><input type="text" title="프로젝트 소개" placeholder="프로젝트 소개를 입력하세요." value="SQL C 구축을 위한 프로젝트입니다. " style="width:100%;" /></td> -->
</tr>
<tr>
	<th scope="row">모니터링 그룹 설명 </th>
	<td>{{ object.mnt_group_desc}} </td>
</tr>
</tbody>
</table><!-- table end -->
</br>

<!-- 검색기능이 없어서 당분간 주석 처리 함 -->
<!--
<aside class="blue_title mt30">
<ul class="search_opt">
	<li>프로젝트 명 검색&nbsp;&nbsp;</li>
	<li><input type="text" title="" placeholder="" style="width:520px;" /></li>
	<li><p class="btn small btn_black"><a href="#">검색</a></p></li>
</ul>
</aside>
-->
<!-- blue_title end -->
<ul class="list_style"><!-- list_style start -->

<h2 class="level2"> 등록사용자 </h2> </br></br>
{% for mnt in object.mntgroupuser_set.all %}
<li>
	<strong> {{ mnt.mntUser.get_username}}  </strong>
    <p class="subject"><a href=""> 그룹정보 :&nbsp;<span> {{ mnt.mntUser.username}} </a></p>
</li>
{% endfor %}
</br>


<h2 class="level2"> 등록 서버  </h2>
{% for mnt in object.mntgroupserver_set.all %}
<li>
	<strong> {{ mnt.ava_server.server_nm }}  </strong>
    <p class="subject"><a href="#"> 서버IP정보 :&nbsp;<span> {{ mnt.ava_server.db_server_ip}} &nbsp;&nbsp; </span> 생성일:&nbsp;  <span> {{ mnt.ava_server.created_dt }} </span> </a></p>
</li>
{% endfor %}
</br>


</ul> <!-- list_style end -->
<p class="btn_more mt20"><a href="#">More</a></p>
</form>
</section><!-- contents end -->

</section><!-- container end -->
<hr />
{% endblock %}

sqlccpjt/pjtmgmt/templates/pjtmgmt/detail_sqlcpjt.html
{% extends "base.html" %}
{% load staticfiles %}
{% block divinfo %} <div id="wrap" ><!-- wrap start --> {% endblock %}
{% block content %}
<section class="container"><!-- container start -->

<section class="contents"><!-- contents start -->
<form action="#" method="post">{% csrf_token %}

<h2 class="level2"> {{ object.project_nm }} 프로젝트 정보 </h2>

<table class="type2 mt30"><!-- table start -->
<caption>table</caption>
<colgroup>
	<col style="width:220px" />
	<col style="width:*" />
</colgroup>
<tbody>
<tr>
	<th scope="row">프로젝트 소개</th>
    <td>{{ object.project_desc.errors }} {{ object.project_desc }} </td>
	<!-- <td><input type="text" title="프로젝트 소개" placeholder="프로젝트 소개를 입력하세요." value="SQL C 구축을 위한 프로젝트입니다. " style="width:100%;" /></td> -->
</tr>
<tr>
	<th scope="row">구매 상품</th>
	<td>{{ object.prod_id}} </td>
</tr>
<tr>
	<th scope="row">프로젝트 유효기간 </th>
	<td>{{ object.sta_eff_dt }} ~ {{ object.end_eff_dt}} </td>
</tr>
<tr>
	<th scope="row">프로젝트 OWNER</th>
	<td> {{ object.owner  }} </td>
</tr>
</tbody>
</table><!-- table end -->
</br>

<!-- 검색기능이 없어서 당분간 주석 처리 함 -->
<!--
<aside class="blue_title mt30">
<ul class="search_opt">
	<li>프로젝트 명 검색&nbsp;&nbsp;</li>
	<li><input type="text" title="" placeholder="" style="width:520px;" /></li>
	<li><p class="btn small btn_black"><a href="#">검색</a></p></li>
</ul>
</aside>
-->
<!-- blue_title end -->

<ul class="right_btns">
	<li><p class="btn btn_orange"><a href="{% url 'addserver' object.id %}">신규 서버 등록<span class="icon_plus_white"></span></a></p></li>
	<li><p class="btn btn_orange"><a href="{% url 'addgroup'  object.id %}">신규 모니터링 그룹 등록<span class="icon_plus_white"></span></a></p></li>
</ul>
<ul class="list_style"><!-- list_style start -->

<h2 class="level2"> 모니터링 그룹 리스트 </h2> </br></br>
{% for mnt in object.mntgroup_set.all %}
<li>
	<strong> {{ mnt.mnt_group_nm }}  </strong>
    <p class="subject"><a href="{% url 'detailmntgrp' mnt.id %}"> 그룹정보 :&nbsp;<span> {{ mnt.mnt_group_desc}} </a></p>
	<ul class="right_btns">
		<li><p class="btn btn_blue"><a href="{% url 'addmntuser' mnt.id object.id %}"> 사용자 추가 <span class="icon_plus_white"> </span> </a></p></li>
		<li><p class="btn btn_green"><a href="{% url 'addmntserver' mnt.id object.id  %}"> 서버 추가 <span class="icon_plus_white"></span></a></p></li>
		<li><p class="btn btn_blue"><a href="{% url 'updateserver' mnt.id %}"> 그룹명 변경 <span class="icon_plus_white"> </span> </a></p></li>
		<li><p class="btn btn_green"><a href="{% url 'delserver' mnt.id %}">그룹삭제<span class="icon_plus_white"></span></a></p></li>
	</ul>
</li>
{% endfor %}
</br>
</br></br>


<h2 class="level2"> 프로젝트 내 등록 서버 리스트 </h2>
{% for mnt in object.mntserver_set.all %}
<li>
	<strong> {{ mnt.server_nm }}  </strong>
    <p class="subject"><a href="#"> 서버IP정보 :&nbsp;<span> {{ mnt.db_server_ip}} &nbsp;&nbsp; </span> 생성일:&nbsp;  <span> {{ mnt.created_dt }} </span> </a></p>
	<p class="date">유효여부 : <span> {{ mnt.is_available }} </span></p>
	<ul class="right_btns">
		<li><p class="btn btn_blue"><a href="{% url 'delserver' mnt.id %}"> 서버 삭제 <span class="icon_plus_white"> </span> </a></p></li>
		<!-- <li><p class="btn btn_green"><a href="{% url 'delserver' mnt.id %}">서버삭제<span class="icon_plus_white"></span></a></p></li> -->
	</ul>
</li>
{% endfor %}
</br>


</ul> <!-- list_style end -->
<p class="btn_more mt20"><a href="#">More</a></p>
</form>
</section><!-- contents end -->

</section><!-- container end -->
<hr />
{% endblock %}